parameters:
        key_name: project-key
        image_Linux: 2d59ed0c-f5a9-4dee-bc80-bf994e620d3c
        image_Windows10: Windows 10 1803 Enterprise Eval
        image_Windows12: Windows Server 2012 R2 Standard
        image_Windows16: Windows Server 2016 Standard
        image_Windows19: Windows Server 2019 Standard Evaluation
        flavor_small: m1.small
        flavor_medium: m1.medium
        flavor_large: m1.large
        public_net: ntnu-internal
        private_net_name: net1
        private_net_cidr: 192.168.196.0/24
        private_net_gateway: 192.168.196.1
        private_net_pool_start: 192.168.196.200
        private_net_pool_end: 192.168.196.250

